export const ResultCode = {
  OK: 0,
  ERROR: 1,
  UNAUTHORIZED: 2,
  WRONG_LOGIN_DATA: 3,
  USER_ALREADY_EXISTS: 4,
  INCORRECT_ACTIVATION_LINK: 5,
  EMAIL_NOT_VERIFIED: 6,
  VALIDATION_ERROR: 7,
  USER_NOT_EXISTS: 8,
  MISSING_FILE: 9
}
